// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt6kzMGCxKSBgE9pXiqMkxEO_ZPTmorjc',
    appId: '1:110987025212:android:0ef4982226071ecdb4dc39',
    messagingSenderId: '110987025212',
    projectId: 'film-quest-247b3',
    storageBucket: 'film-quest-247b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_ikzCVklzwiAvCi64H6u0TPOWZFyID3A',
    appId: '1:110987025212:ios:ea54827b673620e5b4dc39',
    messagingSenderId: '110987025212',
    projectId: 'film-quest-247b3',
    storageBucket: 'film-quest-247b3.appspot.com',
    androidClientId: '110987025212-b4kliemio86lete79uiogmbjt59tb9gf.apps.googleusercontent.com',
    iosClientId: '110987025212-265eflvjacvqfv4i39k3un07ie849hdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.filmQuest',
  );
}
